### ISSUE TITLE
Returns "undefined" on requests made with ajax.

### ISSUE THREAD

**Issue by Filliposniper** [sapics/request-country#3]
I have noticed that your module works perfectly with a normal browser request, but returns undefined with  a request made with ajax.

**Comment by sapics** [comment]
Thank you for report!
I have updated version of request-ip. Please test new version v0.1.4.

If you get undefined or false again, please write your ajax request (req.headers, req.connection, req.socket, req.info).
https://github.com/pbojinov/request-ip#how-it-works

**Comment by sapics** [comment]
@Filliposniper  I close this issue because there are no updates.
I will reopen this issue, if there are more information.
