### ISSUE TITLE
TypeError: requestCountry.default is not a function

### ISSUE THREAD

**Issue by Monabr** [sapics/request-country#5]
Node.js

TypeError: requestCountry.default is not a function

```
import * as requestCountry from "request-country";

const code = requestCountry.default(req, "EN");
```

**Comment by sapics** [comment]
@Monabr Thanks for report!

In Win10 + node12, below code looks work. Could you explain how to reproduce the error?
```
import * as requestCountry from "request-country";
const country = requestCountry.default('1.1.1.1');
console.log(country) // AU
```

**Comment by sapics** [comment]
I will close this issue because there are no updates.
But feel free to comment if you have any information, we will reopen again.
